# Generated by Django 5.1.2 on 2024-11-01 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='mouse_keeper',
        ),
        migrations.AddField(
            model_name='mouse',
            name='weaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mouse',
            name='weaned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='website.mouse'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='mother',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_of', to='website.mouse'),
        ),
        migrations.CreateModel(
            name='CageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cage')),
                ('mouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mouse')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mouse')),
            ],
        ),
        migrations.CreateModel(
            name='MouseKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mouse')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mouse', 'user', 'team')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mouse')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
            options={
                'unique_together': {('project_id', 'mouse_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project_id', 'user_id')},
            },
        ),
    ]
