# Generated by Django 5.1.2 on 2024-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_project_remove_mouse_mouse_keeper_mouse_weaned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cagehistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='earmark',
            field=models.CharField(blank=True, choices=[('TL', 'Top Left'), ('TR', 'Top Right'), ('BL', 'Bottom Left'), ('BR', 'Bottom Right')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='state',
            field=models.CharField(choices=[('alive', 'Alive'), ('breeding', 'Breeding'), ('to_be_culled', 'To Be Culled'), ('deceased', 'Deceased')], default='alive', max_length=12),
        ),
    ]
