# Generated by Django 5.1.2 on 2024-11-03 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_cagehistory_end_date_alter_mouse_earmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('leader', 'Leader'), ('staff', 'Staff'), ('new_staff', 'New Staff'), ('breeder', 'Breeder')], default='new_staff', max_length=10),
        ),
        migrations.CreateModel(
            name='BreedingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cage', models.ForeignKey(help_text='Cage for breeding', on_delete=django.db.models.deletion.CASCADE, to='website.cage')),
                ('female_mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_female_requests', to='website.mouse')),
                ('male_mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_male_requests', to='website.mouse')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CullingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culling_requests', to='website.mouse')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('destination_cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers', to='website.cage')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='website.mouse')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_cage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transfers', to='website.cage')),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
