# Generated by Django 5.1.2 on 2024-11-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_user_role_breedingrequest_cullingrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='genotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breedingrequest',
            name='female_mouse',
            field=models.ForeignKey(limit_choices_to={'sex': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_female_requests', to='website.mouse'),
        ),
        migrations.AlterField(
            model_name='breedingrequest',
            name='male_mouse',
            field=models.ForeignKey(limit_choices_to={'sex': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_male_requests', to='website.mouse'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='earmark',
            field=models.CharField(blank=True, choices=[('TL', 'Top Left'), ('TR', 'Top Right'), ('BL', 'Bottom Left'), ('BR', 'Bottom Right'), ('TLBR', 'Top Left Bottom Right'), ('TLBL', 'Top Left Bottom Left'), ('TRBL', 'Top Right Bottom Left'), ('TRBR', 'Top Right Bottom Right'), ('TLTRBLBR', 'Top Left Top Right Bottom Left Bottom Right')], max_length=20, null=True),
        ),
    ]
