# Generated by Django 5.1.2 on 2024-12-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_user_role_breedingrequest_cullingrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingrequest',
            name='female_mouse',
            field=models.ForeignKey(limit_choices_to={'sex': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_female_requests', to='website.mouse'),
        ),
        migrations.AlterField(
            model_name='breedingrequest',
            name='male_mouse',
            field=models.ForeignKey(limit_choices_to={'sex': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_male_requests', to='website.mouse'),
        ),
    ]
