# Generated by Django 5.1.2 on 2025-02-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_mouse_genotype_mouse_phenotype_and_more'),
        ('website', '0010_alter_mouse_sex_alter_user_profile_picture'),
    ]

    operations = [
    ]
