# Generated by Django 5.1.2 on 2025-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_breedingrequest_requester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotype',
            name='mouse',
        ),
        migrations.AddField(
            model_name='mouse',
            name='genotype',
            field=models.CharField(choices=[('Wild type', 'wt'), ('Heterozygous', 'hat'), ('Knock out', 'ko'), ('N.A.', 'na')], default='na', max_length=20),
        ),
        migrations.DeleteModel(
            name='Genotype',
        ),
        migrations.DeleteModel(
            name='Phenotype',
        ),
    ]
